# Generated by Django 6.0.4 on 2026-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
