# Generated by Django 6.0.4 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
