# Generated by Django 6.0.4 on 2026-06-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customerprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='full_name',
        ),
    ]
