# Generated by Django 6.0.4 on 2026-07-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.customerprofile')),
            ],
        ),
    ]
