# Generated by Django 6.0.4 on 2026-08-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
