# Generated by Django 6.0.4 on 2026-08-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=20),
        ),
    ]
