name: Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::750026323321:role/GitHubActions-ServiceBooking-Deploy
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Deploy using SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-045b645e7bc28a9d4" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Service Booking Platform" \
            --parameters 'commands=["cd /home/ubuntu/service-booking-platform && ./deploy.sh"]'